MOS-115: Convert DataView component from JSX to TSX
simpleviewinc/sv-mosaic pull request #106
Opened 2022-05-26 18:41 UTC by cristianvj23

# What's include:

- Convert DataView component from JSX to TSX
- Created new types for DataView props
- Fixed ts error with Display component type

2022-05-26 21:06 UTC, mauriciodeleonc requested changes

2022-05-26 22:06 UTC, cristianvj23 commented on src/components/DataView/DataViewTypes.ts
> +	component: React.ElementType
Yes, that change fix the type problem with Display component
![image](https://user-images.githubusercontent.com/97243622/170587642-d48fe00b-c2f9-4e1c-9b97-b7e4b4a18dd7.png)

2022-05-26 22:22 UTC, cristianvj23 commented on src/components/DataView/DataViewTypes.ts
> +	(data: void): void
Updated in new commit

2022-05-27 14:56 UTC, mauriciodeleonc approved these changes

2022-05-27 14:59 UTC, merged