Mos 789: All option based fields should have a similar contract
simpleviewinc/sv-mosaic pull request #246
Opened 2022-09-29 00:22 UTC by cristianvj23

# What's include ? 
Refactoring to allow the following form fields to receive options and getOptions as props
- FormFieldCheckbox
- FormFieldChipSingleSelect
- FormFieldAdvanceSelection
- FormFieldRadioButtons
- FormFieldDropdownSingleSelect

2022-10-03 22:45 UTC, mauriciodeleonc requested changes

2022-10-05 18:43 UTC, cristianvj23 commented on src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.tsx
> +						value={value || null}
Apparently if you don't pass null, the component is unable to prepopulate value

2022-10-07 00:01 UTC, mauriciodeleonc approved these changes

2022-10-07 00:02 UTC, mauriciodeleonc approved these changes

2022-10-13 18:49 UTC, mauriciodeleonc approved these changes

2022-10-13 19:36 UTC, merged