MOS-808: Update FormNav tabs logic
simpleviewinc/sv-mosaic pull request #253
Opened 2022-10-07 23:07 UTC by cristianvj23

#What's include?
-Updated form nav logic so tabnav is not displayed when it receives one section
-Added knob to show one or three sections on the form

2022-10-10 23:02 UTC, mauriciodeleonc requested changes

2022-10-10 23:02 UTC, mauriciodeleonc commented on src/components/Form/Form.stories.tsx
> +	const showMultipleSections = boolean("Show multiple sections", true);
Suggestion: We could get rid of this knob and make the "showSections" a select knob with 0, 1, 2, or 3 as options, if 0 then it's like we didn't have options.

2022-10-10 23:02 UTC, mauriciodeleonc commented on src/components/Form/Form.stories.tsx
> +					sections={
If we change the showSections knob to be a select then we can do something like showSections === 0 ? undefined : sections.slice(0, showSections)

2022-10-11 15:09 UTC, cristianvj23 commented on src/components/Form/Form.stories.tsx
> +				{
Yes, if you look at line 428, I'm using .slice() to get the first slice of the array, and it needs the table field to be in the first seven positions of the array.

2022-10-11 18:49 UTC, mauriciodeleonc approved these changes

2022-10-11 18:51 UTC, mauriciodeleonc approved these changes

2022-10-12 19:06 UTC, mauriciodeleonc approved these changes

2022-10-12 19:06 UTC, merged