MOS-809: Matrix field
simpleviewinc/sv-mosaic pull request #336
Opened 2023-01-03 19:05 UTC by JAndresHJGlobant

## What's included?

- FormFieldMatrix component with its respective unit test.
- Form and Browse variants as stories.
- Prop onCheckboxClick added to the DV to know which rows have been checked, related docs added too.

2023-01-04 02:20 UTC, mauriciodeleonc requested changes
Forgot to add another comment. Please export the matrix field in index.ts so it can be consumed with npm.

2023-01-04 16:39 UTC, JAndresHJGlobant commented on src/components/DataView/DataViewLimit/DataViewControlLimit.tsx
> +			value={props?.limit?.toString()}
Is not breaking I set it as optional because I was doing some debugging. I've reverted it.

2023-01-05 02:52 UTC, mauriciodeleonc requested changes

2023-01-05 20:42 UTC, mauriciodeleonc approved these changes

2023-01-05 20:42 UTC, merged