MOS-1127 mindate support
simpleviewinc/sv-mosaic pull request #497
Opened 2023-08-07 12:14 UTC by GeorgeBatt-SV

This PR adds support for a custom `Datepicker` minimum date. By default, MUI sets this minimum date to 01/01/1900, but setting this prop will allow for it to be earlier or later.

2023-08-15 12:45 UTC, Porl91 approved these changes

2023-08-15 13:01 UTC, Porl91 commented
@GeorgeBatt-SV Ah just noticed an error on this page
http://kube.simpleview.io:10000/?path=/story/components-form--playground

It looks like `inputSettings` is optional here so we might want another null propagation.

![image](https://github.com/simpleviewinc/sv-mosaic/assets/13272784/05154c53-cc2e-4a88-a254-ce19a0ba8e26)


![image](https://github.com/simpleviewinc/sv-mosaic/assets/13272784/51204336-cf05-42be-9923-14581abb9e34)

2023-08-15 13:03 UTC, Porl91 requested changes

2023-08-15 13:03 UTC, Porl91 commented on src/forms/FormFieldDate/DateField/FormFieldDate.tsx
> +									placeholder: DATE_FORMAT_FULL_PLACEHOLDER,
!

2023-08-15 14:53 UTC, GeorgeBatt-SV commented on src/forms/FormFieldDate/DateField/FormFieldDate.tsx
> +									placeholder: DATE_FORMAT_FULL_PLACEHOLDER,
Cheers @Porl91, amended.

2023-08-16 09:02 UTC, Porl91 approved these changes

2023-08-16 09:33 UTC, merged